# GoReleaser configuration for TUIOS
# Simple config - just builds binaries and publishes to GitHub releases

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tuios
    main: ./cmd/tuios
    binary: tuios
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

  - id: tuios-web
    main: ./cmd/tuios-web
    binary: tuios-web
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - id: tuios-archive
    name_template: "tuios_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - tuios

  - id: tuios-web-archive
    name_template: "tuios-web_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - tuios-web

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request

release:
  github:
    owner: aptdnfapt
    name: tuios
  draft: false
  prerelease: auto
